# Generated by Django 4.1.3 on 2022-11-18 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "name",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("F", "fundacja"),
                            ("OPZ", "organizacja pozarządowa"),
                            ("ZL", "zbiórka lokalna"),
                        ],
                        default="F",
                        max_length=3,
                    ),
                ),
                ("categories", models.ManyToManyField(to="charitydonation.category")),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("address", models.CharField(max_length=128)),
                ("city", models.CharField(max_length=128)),
                ("zip_code", models.DecimalField(decimal_places=0, max_digits=5)),
                ("pick_up_date", models.DateField()),
                ("pick_up_time", models.TimeField()),
                ("pick_up_comment", models.CharField(max_length=128)),
                ("categories", models.ManyToManyField(to="charitydonation.category")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charitydonation.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
